name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add rust sources
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Add bootimage
      run: cargo install bootimage
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
